# Rolling nightly channel pointer — auto-generated by .github/workflows/nightly.yml.
#
# This file lives on the `nightly` git ref. The hashes and version below
# match the artifacts published in the current rolling nightly release.
# This file is NOT present on `main` with real hashes — always consume via
# the `nightly` ref:
#
#   nix run github:0xErwin1/dbflux/nightly#dbflux-nightly
#
# From-source nightly (no hash needed):
#
#   nix run github:0xErwin1/dbflux/nightly#dbflux-source
{
  version = "0.8.0-nightly+2b8fb54";

  artifacts = {
    "x86_64-linux" = {
      url = "https://github.com/0xErwin1/dbflux/releases/download/nightly/dbflux-linux-amd64.tar.gz";
      hash = "sha256-ft37zfkWbH1Ybh9X4EH4tNsyXKbryOioBKDbu6uHD/g=";
    };
    "aarch64-linux" = {
      url = "https://github.com/0xErwin1/dbflux/releases/download/nightly/dbflux-linux-arm64.tar.gz";
      hash = "sha256-L7z23tiWvPO7hks+hybDhMPwLb599VCHwVdMwos03rA=";
    };
  };
}
